server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://118.89.20.37/test1?allowMultiQueries=true&useUnicode=true&amp;characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: dev
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
#  profiles:
#    include: common
user.name: guojie
user.age: 28

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml